version: "3.9"

include:
  - users-service/deploy/docker-compose.yaml
  - products-service/deploy/docker-compose.yaml
  - orders-service/deploy/docker-compose.yaml
  - reviews-service/deploy/docker-compose.yaml
  - security-service/deploy/docker-compose.yaml
  - chat-service/deploy/docker-compose.yaml
  - api-gateway-service/deploy/docker-compose.yaml

networks:
  default:
    driver: bridge
