version: "3.9"

services:
  users-mariadb:
    image: mariadb:11
    container_name: users-mariadb-service
    environment:
      MARIADB_ROOT_PASSWORD: oWhB9-HW
      MARIADB_DATABASE: usersdb
      MARIADB_USER: usersService
      MARIADB_PASSWORD: glf-Jj6A
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - users-db-data:/var/lib/mysql

  users-service:
    container_name: users-service
    build:
      context: ./users-service
    ports:
      - "3001:3000"
    depends_on:
      users-mariadb:
        condition: service_healthy
    environment:
      DATABASE_HOST: users-mariadb
      DATABASE_PORT: 3306
      DATABASE_USER: usersService
      DATABASE_PASSWORD: glf-Jj6A
      DATABASE_NAME: usersdb

  products-mariadb:
    image: mariadb:11
    container_name: products-mariadb-service
    environment:
      MARIADB_ROOT_PASSWORD: 6-L2fPxG
      MARIADB_DATABASE: productsdb
      MARIADB_USER: productsService
      MARIADB_PASSWORD: 00nE_QmO
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - products-db-data:/var/lib/mysql

  products-service:
    container_name: products-service
    build:
      context: ./products-service
    ports:
      - "3002:3000"
    depends_on:
      products-mariadb:
        condition: service_healthy
    environment:
      DATABASE_HOST: products-mariadb
      DATABASE_PORT: 3306
      DATABASE_USER: productsService
      DATABASE_PASSWORD: 00nE_QmO
      DATABASE_NAME: productsdb

  orders-mongodb:
    image: mongo:7
    container_name: orders-mongodb-service
    ports:
      - "27017:27017"
    volumes:
      - orders-db-data:/data/db

  orders-service:
    container_name: orders-service
    build:
      context: ./orders-service
    ports:
      - "3003:3000"
    depends_on:
      - orders-mongodb
    environment:
      MONGODB_URI: mongodb://orders-mongodb:27017/orders

  reviews-mongodb:
    image: mongo:7
    container_name: reviews-mongodb-service
    ports:
      - "27018:27017"
    volumes:
      - reviews-db-data:/data/db

  reviews-service:
    container_name: reviews-service
    build:
      context: ./reviews-service
    ports:
      - "3005:3000"
    depends_on:
      - reviews-mongodb
    environment:
      MONGODB_URI: mongodb://reviews-mongodb:27017/reviews

  security-mongodb:
    image: mongo:7
    container_name: security-mongodb-service
    ports:
      - "27019:27017"
    volumes:
      - security-db-data:/data/db

  security-service:
    container_name: security-service
    build:
      context: ./security-service
    ports:
      - "3006:3000"
    depends_on:
      - security-mongodb
    environment:
      MONGODB_URI: mongodb://security-mongodb:27017/security
      JWT_SECRET: your_secure_jwt_secret_key
      JWT_REFRESH_SECRET: your_secure_refresh_secret_key

  chats-service:
    container_name: chats-service
    build:
      context: ./chat-service
    ports:
      - "3004:3000"

  api-gateway-service:
    container_name: api-gateway-service
    build:
      context: ./api-gateway-service
    ports:
      - "3000:3000"
    depends_on:
      - users-service
      - products-service
      - orders-service
      - reviews-service
      - chats-service
      - security-service

volumes:
  users-db-data:
  products-db-data:
  orders-db-data:
  reviews-db-data:
  security-db-data:
